### ISSUE TITLE
Multimedia keys support

### ISSUE THREAD

**Issue by hexchain** [christophgysin/pasystray#92]
It would be great if this applet supports XF86 multimedia keys.

**Comment by aadityabagga** [comment]
As a workaround, I assign the following keys in my window manager (fluxbox):

~~~~
XF86AudioRaiseVolume :Exec pactl set-sink-volume @DEFAULT_SINK@ +5%
XF86AudioLowerVolume :Exec pactl set-sink-volume @DEFAULT_SINK@ -5%
XF86AudioMute :Exec pactl set-sink-mute @DEFAULT_SINK@ toggle
~~~~

Additionally have set **flat-volumes = no** in _/etc/pulse/daemon.conf_ so that changing the sink/device volume does not affect the source/application volume.
